"""add image_hash column

Revision ID: 3260039d9602
Revises: ff9b1d6fbb77
Create Date: 2026-04-08 00:13:23.081466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3260039d9602'
down_revision: Union[str, None] = 'ff9b1d6fbb77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('image_hash', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'image_hash')
    # ### end Alembic commands ###
