"""initial tables

Revision ID: ff9b1d6fbb77
Revises: 
Create Date: 2026-04-07 13:46:23.851322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff9b1d6fbb77'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('target_currency', sa.String(length=3), nullable=False),
    sa.Column('rate', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('rate_date', sa.Date(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('base_currency', 'target_currency', 'rate_date')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('original_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('original_currency', sa.String(length=3), nullable=False),
    sa.Column('eur_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('exchange_rate', sa.Numeric(precision=12, scale=6), nullable=True),
    sa.Column('location_city', sa.String(length=255), nullable=True),
    sa.Column('location_country', sa.String(length=100), nullable=True),
    sa.Column('receipt_path', sa.String(length=500), nullable=True),
    sa.Column('receipt_thumbnail_path', sa.String(length=500), nullable=True),
    sa.Column('line_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('raw_llm_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_expenses_category', 'expenses', ['telegram_user_id', 'category'], unique=False)
    op.create_index('idx_expenses_location', 'expenses', ['telegram_user_id', 'location_country', 'location_city'], unique=False)
    op.create_index('idx_expenses_user_date', 'expenses', ['telegram_user_id', 'date'], unique=False)
    op.create_index('idx_expenses_vendor', 'expenses', ['telegram_user_id', 'vendor'], unique=False)
    op.create_table('scheduled_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('frequency', sa.String(length=20), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=True),
    sa.Column('day_of_month', sa.SmallInteger(), nullable=True),
    sa.Column('time_utc', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('send_telegram', sa.Boolean(), nullable=False),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scheduled_reports')
    op.drop_index('idx_expenses_vendor', table_name='expenses')
    op.drop_index('idx_expenses_user_date', table_name='expenses')
    op.drop_index('idx_expenses_location', table_name='expenses')
    op.drop_index('idx_expenses_category', table_name='expenses')
    op.drop_table('expenses')
    op.drop_table('exchange_rates')
    # ### end Alembic commands ###
